FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    pkg-config \
    libssl-dev \
    libpq-dev \
    libpqxx-dev \
    libargon2-dev \
    libboost-system-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN rm -rf build

EXPOSE 8080
EXPOSE 8081
EXPOSE 8082

CMD ["sleep", "infinity"]