// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_TeamsClient_Core)
QT_DECLARE_EXTERN_RESOURCE(qmake_TeamsClient)
QT_DECLARE_EXTERN_RESOURCE(TeamsClient_Core_raw_qml_0)
QT_DECLARE_EXTERN_RESOURCE(TeamsClient_Core_raw_qml_0_extra_qmldirs)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_TeamsClient)

class TeamsClientPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    TeamsClientPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_TeamsClient)
QT_KEEP_RESOURCE(qmlcache_TeamsClient_Core)
QT_KEEP_RESOURCE(qmake_TeamsClient)
QT_KEEP_RESOURCE(TeamsClient_Core_raw_qml_0)
QT_KEEP_RESOURCE(TeamsClient_Core_raw_qml_0_extra_qmldirs)
    }
};



#include "TeamsClient_Coreplugin_TeamsClientPlugin.moc"
